### ISSUE TITLE
IE11无法调起打印

### ISSUE THREAD

**Issue by crazydawnhzbin** [Power-kxLee/vue-print-nb#104]
插件版本:1.7.4
浏览器版本: IE11
写了个最简单的demo，在chorme上能运行，在IE11上调不起打印，提示：nullError: 找不到成员。
注:仅打印，没设置preview,设置了preview也不行

**Comment by Power-kxLee** [comment]
ie不能支持 preview

**Comment by crazydawnhzbin** [comment]
> ie不能支持 preview

你好！哪怕是不设置preview也调不起打印
