### ISSUE TITLE
打印之前div是隐藏的，点击打印内容为空

### ISSUE THREAD

**Issue by haiyang1024** [Power-kxLee/vue-print-nb#105]
打印之前div是隐藏的，点击打印chrome显示内容为空，再打印之前的回调事件 设置为显示div ，chrome显示的内容还是空，这个怎么解决呢

**Comment by Power-kxLee** [comment]
你打印div是空的内容 ？

**Comment by haiyang1024** [comment]
是的，预览的时候也是空的

**Comment by haiyang1024** [comment]
@Power-kxLee 是的，预览的时候也是空的

**Comment by haiyang1024** [comment]
已解决，外面在套一层div隐藏就行了
