### ISSUE TITLE
监听不到打印事件

### ISSUE THREAD

**Issue by n19ht** [Power-kxLee/vue-print-nb#115]
window.onbeforeprint = (event) => {
  console.log('Before print');
};，使用这个插件监听不到打印事件了

**Comment by dyywork** [comment]
可以试试这个vue-print-nb-dom-show

**Comment by Power-kxLee** [comment]
看demo啊 完全不是这样写

**Comment by n19ht** [comment]
> 看demo啊 完全不是这样写

你没明白我想要表达的意思，如果我使用这个打印插件，那我用原生的方式window.onbeforeprint监听不到onbeforeprint事件，而不是是使用打印组件提供的的onbeforeprint事件，我知道你组件提供了这个钩子
