### ISSUE TITLE
打印无内容

### ISSUE THREAD

**Issue by Gliese129** [Power-kxLee/vue-print-nb#116]
使用element plus的timeline组件并且打印时发现内容为空白，element样式已在extra css中引入
在preview预览后发现，timeline中的ul和li中只有ul被拉到了打印的iframe标签中
![image](https://user-images.githubusercontent.com/32563762/130347021-e6445f2d-bc57-431e-bad8-b9fdd05324cc.png)
原来的dom元素
![image](https://user-images.githubusercontent.com/32563762/130347076-df5ce99d-0d60-4f61-9b30-3c75e91540ac.png)
print nb拉过来的dom元素

**Comment by Power-kxLee** [comment]
上代码
