### ISSUE TITLE
Error in nextTick: "SyntaxError: Failed to execute 'querySelector' on 'Document': '[object Object]' is not a valid selector."

### ISSUE THREAD

**Issue by ghdestiny** [Power-kxLee/vue-print-nb#16]
Error in nextTick: "SyntaxError: Failed to execute 'querySelector' on 'Document': '[object Object]' is not a valid selector."

why???

**Comment by Power-kxLee** [comment]
What browser is it?

**Comment by YoungHF** [comment]
> What browser is it?

I have the same problem，can you solve it ? Thanks~

**Comment by Power-kxLee** [comment]
Updated version

**Comment by daliborjelinek** [comment]
I have same issue even if I have latest version. With `v-print="'#printMe'"` is everything ok but when I use `v-print="printObj"` I've get this error.  It seems like it recognize given object as a string and trying to use it as html selector.

**Comment by SnowZhouJ** [comment]
@Power-kxLee  我也有他@daliborjelinek 的这个情况，在使用v-print="printObj时出现此问题。
DOMException: Failed to execute 'querySelector' on 'Document': '[object Object]' is not a valid selector.
    at t.value (webpack-internal:///./node_modules/vue-print-nb/lib/tag-textarea.umd.min.js:1:31258)

**Comment by DawnL6** [comment]
这个问题有解决吗
