### ISSUE TITLE
这个插件对于谷歌浏览器的版本有要求，请问最低支持到什么版本？

### ISSUE THREAD

**Issue by leafinwindljf** [Power-kxLee/vue-print-nb#22]
这个插件对于谷歌浏览器的版本有要求，请问最低支持到什么版本？
目前发现如果谷歌浏览器的版本是65，那么打印预览是无法生产的，当然打印也是空白。
而75以上，就是可以的。
想确认一下，这个大概什么版本以下是无法使用此插件的？
同时，也想咨询下如何可以兼容所有版本？

**Comment by Power-kxLee** [comment]
我下载了几个浏览器版本 18年的65  17年的61 都没问题。具体排查一下代码错误的地方 把错误的提示贴上来
