### ISSUE TITLE
如何设置默认选中打印背景色？

### ISSUE THREAD

**Issue by leafinwindljf** [Power-kxLee/vue-print-nb#23]
在打印时，有的人浏览器默认好像是不选中那个“背景图片”的选项。这样所有设置北京颜色的样式都会失效。但是，实际使用中，是需要打印背景的。但是不是每个人都会设置。如果能用代码控制是最好的。所以，是不是有什么设置？或者什么样式，可以让这个操作由程序控制完成。

**Comment by Power-kxLee** [comment]
打印的时候不支持带颜色，打印控件里面勾选一下就行了
![image](https://user-images.githubusercontent.com/13028354/62831320-ab118080-bc4f-11e9-956a-9e59fa7cf003.png)
