### ISSUE TITLE
顺便咨询个现象，是不是打印设置了box-sizing: content-box？

### ISSUE THREAD

**Issue by leafinwindljf** [Power-kxLee/vue-print-nb#24]
现在打印预览的时候，如果使用box-sizing: content-box的情况，问题会少很多。如果使用了box-sizing: border-box;布局基本都会崩掉。这个可以设置么？

**Comment by Power-kxLee** [comment]
这个布局跟你打印的纸张大小有影响的。你纸张大一点 布局自然大一点
