### ISSUE TITLE
反馈并咨询各问题，关于读取样式路径的问题

### ISSUE THREAD

**Issue by leafinwindljf** [Power-kxLee/vue-print-nb#27]
原本以为是相对路径和绝对路径的问题。经过反复的测试。确定问题是跨域的问题。
也就是如果使用了CDN，而恰巧是别的域名，这个打印功能就不能使用了。
这个插件有BUG，需要修改那个循环读style的地方，做各判断，如果读不到正确的信息，或者发现跨域，就可以忽略，跳到下一个。毕竟link标签在前边也已经处理了，所以，这个针对style的地方。之做好判断即可。

**Comment by Power-kxLee** [comment]
thx 已修复
