### ISSUE TITLE
v-print="'#printMe'"无效; v-print可以打印整个页面

### ISSUE THREAD

**Issue by 857128237** [Power-kxLee/vue-print-nb#28]
我在子组件里面用v-print="'#printMe'"  也设置了id 但是没有用,只有v-print的时候整个页面可以打印

**Comment by vampireXia** [comment]
我也遇到这问题 请问怎么解决

**Comment by Power-kxLee** [comment]
写法错了 直接传入 v-print="printMe" 就可以 @857128237 @vampireXia
