### ISSUE TITLE
.cssRules & .rules properties blocked by Chrome

### ISSUE THREAD

**Issue by webbtj** [Power-kxLee/vue-print-nb#3]
As of Chrome 64 (https://stackoverflow.com/a/49160899) CORS rules are now enforced which prevent accessing properties like `.cssRules` and `.rules` on remote CSS files. Line 68 of `/src/printarea.js` attempts to access these properties with no handling of the new security limitations. Perhaps you'll want to only use style sheet elements where the domain matches, some type of configuration to allow users to skip certain style sheets, or just another method of including the styles.

**Comment by r9software** [comment]
can you propose something? I have downloaded this and I have this error too, and the vue plugin seems to be outdated

**Comment by Power-kxLee** [comment]
hello，you Chrome version number？
