### ISSUE TITLE
传入对象类型会报错

### ISSUE THREAD

**Issue by LIYUNLIN** [Power-kxLee/vue-print-nb#33]
`<div id="printTest"><p style="color: red">明月照于山间</p><p>清风来于江上</p></div>      <button v-print="printObj">打印</button>`

data() {
    return {
      printObj: {
        id: 'printTest',
        popTitle: 'good print',
        extraCss: 'https://www.google.com,https://www.google.com',
        extraHead: '<meta http-equiv="Content-Language"content="zh-cn"/>'
      }
    }
  }
报错： [Vue warn]: Error in nextTick: "SyntaxError: Failed to execute 'querySelector' on 'Document': '[object Object]' is not a valid selector."

**Comment by wang-chong** [comment]
@Power-kxLee 源码下载后运行没问题，估计是打包插件或者配置的问题
打包后代码里面没有判断传入的是字符串还是对象，打包后代码如下
![image](https://user-images.githubusercontent.com/24750038/63989075-90754d80-cb11-11e9-9d0b-49eba7bfd9f3.png)
解决办法：
不改配置的情况下：修改print.js里面局部打印那里的代码，通过传参的方式传入id，修改后如下
![image](https://user-images.githubusercontent.com/24750038/63989146-e21dd800-cb11-11e9-8844-737f2de767f0.png)

**Comment by smm5120** [comment]
请问得到解决办法了吗

**Comment by Power-kxLee** [comment]
请更新最新代码
