### ISSUE TITLE
在打印  el-tabs  里面的内容时，只有第一页有效，后面的为空白

### ISSUE THREAD

**Issue by mq1355066061** [Power-kxLee/vue-print-nb#43]

**Comment by Power-kxLee** [comment]
请提供详细的信息

**Comment by mq1355066061** [comment]
已解决，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kxlee"<notifications@github.com&gt;; 
发送时间: 2020年1月14日(星期二) 下午4:49
收件人: "Power-kxLee/vue-print-nb"<vue-print-nb@noreply.github.com&gt;; 
抄送: "JL"<1355066061@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Power-kxLee/vue-print-nb] 在打印  el-tabs  里面的内容时，只有第一页有效，后面的为空白 (#43)




请提供详细的信息

**Comment by rainbow516red** [comment]
> 已解决，谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kxlee"<notifications@github.com&gt;; 发送时间: 2020年1月14日(星期二) 下午4:49 收件人: "Power-kxLee/vue-print-nb"<vue-print-nb@noreply.github.com&gt;; 抄送: "JL"<1355066061@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [Power-kxLee/vue-print-nb] 在打印 el-tabs 里面的内容时，只有第一页有效，后面的为空白 (#43) 请提供详细的信息 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
请问您是怎么解决的。我也遇到这个问题了，打包服务器部署后 ，打印预览只有第一页
