### ISSUE TITLE
Printing Graphics

### ISSUE THREAD

**Issue by ingodahn** [Power-kxLee/vue-print-nb#45]
I have added to my project a button to print as a separate component and imported vue-print-nb in main.js.

The components to be printed include graphics generated with vue-chartjs.
The graphics print fine when I print the whole page. However when printing only a part of the page using v-print="'#ID'", only empty frames for the graphics are shown in print preview. 

When I pass the id in a printObj, nothing is printed and the console shows an error that [object: Object] is not a valid selector.

**Comment by Power-kxLee** [comment]
Updated version Thank！

**Comment by ingodahn** [comment]
The new version still doesn't print the graphics from vue-chartjs. In fact it prints the requested dom object but the graphics are not there, in the new version also the borders of the graphics are not shown. This holds for both the printOnj version as well as the `"'#printArea'"` version. The full page print is still fine.

**Comment by Power-kxLee** [comment]
> 新版本仍然无法从vue-chartjs打印图形。实际上，它会打印所请求的dom对象，但是图形不在那里，在新版本中，图形的边框也没有显示。这适用于printOnj版本以及该`"'#printArea'"`版本。整页打印仍然可以。

Echarts is OK 
vue-chartjs Let me see what happened
