### ISSUE TITLE
怎么去除页眉和页脚呢

### ISSUE THREAD

**Issue by weiyiban** [Power-kxLee/vue-print-nb#5]

**Comment by Power-kxLee** [comment]
打印的时候设置就行了

**Comment by InsHomePgup** [comment]
是什么配置呢？我想去掉左下角的网址信息。。。

**Comment by gouxinjie** [comment]
/* 去除默认页眉和页脚 */
@page {
  size: auto; /* 自动页面大小 */
  margin: 5mm 5mm 5mm 5mm; //打印边距-会影响页眉页脚显示
}

**Comment by gouxinjie** [comment]
css加上 上面代码 就行了 ,或者直接设置margin:0;即可
