### ISSUE TITLE
Doesn't work on iOS or OSX Safari

### ISSUE THREAD

**Issue by SteveCorbett** [Power-kxLee/vue-print-nb#50]
The print function fails on Safari on iOS 13.3.1 and OSX 10.15.3 (and probably earlier versions too). The error "TypeError: undefined is not an object (evaluating 'n.onload=function(){r()}')" is logged to the console.
<img width="1367" alt="Safari 2020-03-05 22 08 40" src="https://user-images.githubusercontent.com/5914933/75976145-f661e800-5f2d-11ea-87e3-3209a382bf84.png">

**Comment by Power-kxLee** [comment]
update 1.7.0
