### ISSUE TITLE
当开打打印窗口后所有字体图标被隐藏

### ISSUE THREAD

**Issue by bayichutou** [Power-kxLee/vue-print-nb#51]
调用print前
![image](https://user-images.githubusercontent.com/61345520/76688965-c7a1eb00-666c-11ea-9d69-128d47e6a317.png)
![image](https://user-images.githubusercontent.com/61345520/76689048-6c242d00-666d-11ea-873a-49ec40c55af5.png)

调用print后
![image](https://user-images.githubusercontent.com/61345520/76688987-e7d1aa00-666c-11ea-9bc5-dca5adba7bca.png)
![image](https://user-images.githubusercontent.com/61345520/76689043-60d10180-666d-11ea-8a4e-47121169db38.png)

**Comment by zhujingxia** [comment]
兄弟，你解决这个问题了吗？我也是图片打印显示为空白

**Comment by Power-kxLee** [comment]
更新1.7.0

**Comment by bayichutou** [comment]
没有解决发自我的荣耀手机-------- 原始邮件 --------发件人： zhujingxia ***@***.***>日期： 2021年4月27日周二 16:31收件人： Power-kxLee/vue-print-nb ***@***.***>抄送： bayichutou ***@***.***>, Author ***@***.***>主    题： Re: [Power-kxLee/vue-print-nb] 当开打打印窗口后所有字体图标被隐藏 (#51)

兄弟，你解决这个问题了吗？我也是图片打印显示为空白
