### ISSUE TITLE
发现checkbox和radio在打印的时候被全选中了

### ISSUE THREAD

**Issue by muliubing7825** [Power-kxLee/vue-print-nb#52]
您好，在页面上含有checkbox和radio的时候，打印预览全部被选中了，
iframe里面的html代码 为checked="false" ,貌似打印的时候不认，认为这都是选中
您有什么解决方案么

**Comment by wwwdada** [comment]
> 您好，在页面上含有checkbox和radio的时候，打印预览全部被选中了，
> iframe里面的html代码 为checked="false" ,貌似打印的时候不认，认为这都是选中
> 您有什么解决方案么

这个问题我也遇见了， 现在解决了吗

**Comment by muliubing7825** [comment]
> > 您好，在页面上含有checkbox和radio的时候，打印预览全部被选中了，
> > iframe里面的html代码 为checked="false" ,貌似打印的时候不认，认为这都是选中
> > 您有什么解决方案么
> 
> 这个问题我也遇见了， 现在解决了吗

解决了，在使用的时候不要使用checked='true'控制选中，要直接使用checked控制，例如：
`<input type="radio" checked/>`
未选中的实例：
`<input type="radio" />`
即可解决问题

**Comment by wwwdada** [comment]
> > > 您好，在页面上含有checkbox和radio的时候，打印预览全部被选中了，
> > > iframe里面的html代码 为checked="false" ,貌似打印的时候不认，认为这都是选中
> > > 您有什么解决方案么
> > 
> > 
> > 这个问题我也遇见了， 现在解决了吗
> 
> 解决了，在使用的时候不要使用checked='true'控制选中，要直接使用checked控制，例如：
> `<input type="radio" checked/>`
> 未选中的实例：
> `<input type="radio" />`
> 即可解决问题

那checkbox 好像还是存在这个问题，我用<input type="checkbox"> 好像都会被选中

**Comment by jiagouview** [comment]
用vue的话该怎么写呢？我也碰到这个问题了。<input type="checkbox" :checked="isCheck"/> isCheck是个变量。该怎么写，求大佬帮助。

**Comment by jiagouview** [comment]
<input type="radio" checked/>我这样写了，问题还是存在呢？打印时checkbox依然全部选中了。

**Comment by jiagouview** [comment]
有没有大佬说一下解决方法。
(<input type="radio" checked/>
未选中的实例：
<input type="radio" />。)
这种解决方法在我这里不生效。

**Comment by tjNane** [comment]
不解决么难道

**Comment by tjNane** [comment]
vue用这个完全没办法搞checkbox，还是vue的包，也是醉了

**Comment by qq159217** [comment]
还是弃用

**Comment by Power-kxLee** [comment]
已更新修复 1.6.0

**Comment by febaoshan** [comment]
https://github.com/Power-kxLee/vue-print-nb/blob/933c5a9658bf197d8c4adf97eaf27b10f13757ad/print/packages/printarea.js#L261

这段代码的问题，input为checkbox或者radio默认渲染的是其checked的attribute值，checked值是一个boolean类型，有不有这个attribute决定了是否为选中状态。代码逻辑不管被打印元素的原始值是否选中，都会给checked赋值一个字符串，所以都会渲染上选中。checked="false"也是会渲染的。

如果需要动态改变checbox和radio需要用dom.checked来改变。

这个问题已经有不少人修复过了，比如：https://www.npmjs.com/package/vue-print-yangyang、https://www.npmjs.com/package/vue-print-qj。

我也修复并发不了一个用于jeecg的版本，https://www.npmjs.com/package/vue-print-nb-jeecg-fixed。

希望作者大佬修复下。@[Power-kxLee](https://github.com/Power-kxLee)
