### ISSUE TITLE
ie下打印报错

### ISSUE THREAD

**Issue by walkingWhite** [Power-kxLee/vue-print-nb#57]
vue项目中我使用的是局部引用
部分代码如下：
`<template>

	<div v-if="data.config"  >
		<p  v-print="printObj"> 打印</p>
		<div id="printMe">
	                              按规定哈哈看到看看
		</div>
	</div>
</template>

<script>

	import print from 'vue-print-nb'
	
	export default {
		name: "fm-generate-form",
		components: {
		},
		props: [],
		data() {
			return {
				models: {},
				rules: {},
				dialogTableVisible: false,
				open: true,
				hasSetList: [], //存放有设置点击设置的控件
				printObj: {
					id: "printMe",
					popTitle: 'good print',
					extraCss: '',
					extraHead: '<meta http-equiv="Content-Language"content="zh-cn"/>'
				}
			};
		},
	directives: {
    	print   
	},
		created() {
			
		},
		methods: {
}		
</script>`
报错信息
SCRIPT5007: 无法设置未定义或 null 引用的属性“onload”
ie错误信息点进去定位到了这里
<link href="0.js" rel="prefetch"><link href="1.js" rel="prefetch"><link href="2.js" rel="prefetch"><link href="3.js" rel="prefetch"><link href="4.js" rel="prefetch"><link href="5.js" rel="prefetch"><link href="6.js" rel="prefetch"><link href="7.js" rel="prefetch"><link href="8.js" rel="prefetch"><link href="app.js" rel="preload" as="script"></head>

**Comment by ai110505** [comment]
我也遇到了同样的问题，求解决

**Comment by yuanyuan-xy** [comment]
大佬解决了吗,求助~~

**Comment by ai110505** [comment]
没有，我们抛弃了IE





------------------ 原始邮件 ------------------
发件人: yuanyuan-xy <notifications@github.com&gt;
发送时间: 2020年9月1日 13:46
收件人: Power-kxLee/vue-print-nb <vue-print-nb@noreply.github.com&gt;
抄送: ai110505 <496199902@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Power-kxLee/vue-print-nb] ie下打印报错 (#57)





 
大佬解决了吗,求助~~

**Comment by anyezhishang** [comment]
需要增删一些代码才能兼容ie

**Comment by Power-kxLee** [comment]
已更新修复 1.6.0
