### ISSUE TITLE
IE兼容问题

### ISSUE THREAD

**Issue by th-520** [Power-kxLee/vue-print-nb#7]
![_20181022200243](https://user-images.githubusercontent.com/20639456/47291260-8bb05500-d635-11e8-9b07-185b57d1aa29.png)
![_20181022200656](https://user-images.githubusercontent.com/20639456/47291407-13965f00-d636-11e8-88a7-d5bfdd3b0c3d.png)

**Comment by qingqiuerpan** [comment]
在ie11上报错：“Error in nextTick: "TypeError: 对象不支持“forEach”属性或方法"”，请问知道是什么原因吗？

**Comment by Power-kxLee** [comment]
已经修复拉，install一下
