### ISSUE TITLE
打印图片不显示

### ISSUE THREAD

**Issue by 13100967125** [Power-kxLee/vue-print-nb#81]
我使用这个插件打印一个带有图片的页面，样式正常，但是图片不显示
 "vue-print-nb": "^1.6.0",

**Comment by foreverfang** [comment]
如果是canvas图片要转换一下图片格式，图片再转base64就可以显示了。

**Comment by Power-kxLee** [comment]
更新1.7.0版本 谢谢

**Comment by Power-kxLee** [comment]
更新1.7.0版本 谢谢
