### ISSUE TITLE
1.6.1报错e.value.beforeOpenCallback is not a function

### ISSUE THREAD

**Issue by yangxiuy** [Power-kxLee/vue-print-nb#90]
大佬你好
更新版本到1.6.1报错：
vue.min.js:6 TypeError: e.value.beforeOpenCallback is not a function
锁定版本在1.6.0就没问题

**Comment by zl19900228** [comment]
我用1.6.0版本也报错：
vue.runtime.esm.js:1888 TypeError: t.value.beforeOpenCallback is not a function

**Comment by Power-kxLee** [comment]
更新1.7.0版本
