### ISSUE TITLE
v-print =“‘#idName’” 使用的时候只能打印预览整个页面，而不是指定id的部分

### ISSUE THREAD

**Issue by kikikuk** [Power-kxLee/vue-print-nb#92]

**Comment by Power-kxLee** [comment]
你试试用字面量对象的方法传入

**Comment by kikikuk** [comment]
> 你试试用字面量对象的方法传入

能具体说明一下么，不太明白是什么意思，谢谢

**Comment by OnlookersLI** [comment]
请问解决了嘛！我也遇到了这个bug！

**Comment by Power-kxLee** [comment]
v-print="printObj"

printObj: {
      id: "idName"
}

**Comment by Power-kxLee** [comment]
> > 你试试用字面量对象的方法传入
> 
> 能具体说明一下么，不太明白是什么意思，谢谢

v-print="printObj"

printObj: {
id: "idName"
}

**Comment by kikikuk** [comment]
> > > 你试试用字面量对象的方法传入
> > 
> > 
> > 能具体说明一下么，不太明白是什么意思，谢谢
> 
> v-print="printObj"
> 
> printObj: {
> id: "idName"
> }

可以了，谢谢

**Comment by kikikuk** [comment]
您好，采用了字面量对象传入之后，火狐浏览器就没有办法调起打印的功能了，直接穿入id才可以调起打印的功能，版本是1.7.3
